version: '3'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app  
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_test:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: app_test
      POSTGRES_USER: app_test
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
volumes:
  postgres_data:
  postgres_data_test:
