version: "3"

services:
  db:
    image: postgres:12-alpine
    container_name: db
    restart: always
    environment:
      #POSTGRES_MULTIPLE_DATABASES: app,app_test
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  app:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bin/rails s -p 3000 -b '0.0.0.0'
    container_name: app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
